### ISSUE TITLE
Fetching Realtime buffer data

### ISSUE THREAD

**Issue by SutirthaChakraborty** [Wonder-Tree/PoseCamera#11]
Hi,

Thank you for this lovely SDK. I am trying to explore this library.
My intension is to calculate the movement of individuals using pose estimation.

How can I implement PoseCamera on video/webcam data in realtime?  And get the estimation value in a  small buffer data (maybe of 4 secs ) to further process it, to find the movement in each individual. I am trying to use google colab for it.  Any example notebook?

Regards,
Suti

**Comment by usmankaiz** [comment]
The SDK can be work for a real-time scenario like web cameras and it can also be used with offline videos. What exactly do you mean by a small buffer of 4 sec?

You can collect the joints data from the SDK and store data according to the frame number. it's up to you how you want to store the joints data in a file either JSON or XML.

Hope this helps.

**Comment by SutirthaChakraborty** [comment]
Thank you for the reply. I understood now. How can I implement it on Windows?

**Comment by SutirthaChakraborty** [comment]
When I am running this code. It's too slow to be real-time. Any way to make it fast?

		while(True):

			ret, frame = cap.read()

			gray= cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
			gray= cv2.resize(frame,(870, 576))

			poses= posecamera.estimate(frame )
			for pose in poses:
				pose.draw(gray)

			cv2.imshow('frame',gray)
			if cv2.waitKey(1) & 0xFF == ord('q'):
				break

		cap.release()

**Comment by usmankaiz** [comment]
Can you share your system specs?

**Comment by SutirthaChakraborty** [comment]
Hi,
OS: Windows 10
RAM : 16 GB 
Memory: 512 GB
Processor: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx, 2300 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by usmankaiz** [comment]
These are some requirements that you need to run the following repository
Python >= 3.6
CUDA 10.1 and Cudnn
