### ISSUE TITLE
module 'posecamera' has no attribute 'load'

### ISSUE THREAD

**Issue by senemaktas** [Wonder-Tree/PoseCamera#13]
Hi ,

Thank you for PoseCamera! 

I installed it on my Linux machine and trying to run it on the Jupyter notebook. 
But I get at the below error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
      4 # !wget https://storage.googleapis.com/wt_storage/lightweight_pose_estimation.pth
      5 
----> 6 posecamera.load("lightweight_pose_estimation.pth")
      7 
      8 image = cv2.imread("3.jpeg")

**AttributeError: module 'posecamera' has no attribute 'load'**

```

**Comment by senemaktas** [comment]
I get same error on Google Colab as well.

**Comment by usmankaiz** [comment]
Hi @senemaktas, 

we have made major changes to the repository, we will be updating the docs and Google Collab File

**Comment by senemaktas** [comment]
Thank you for your feedback. I am looking forward to the changes.

**Comment by usmankaiz** [comment]
Just made few changes for you.
you can use the following link,
it bit rough, will update the notebook
https://colab.research.google.com/drive/1YYEn3YQ6kLvQ-AfR2C_--s40arhhxSuw?usp=sharing

**Comment by senemaktas** [comment]
> Just made few changes for you.
> you can use the following link,
> it bit rough, will update the notebook
> https://colab.research.google.com/drive/1YYEn3YQ6kLvQ-AfR2C_--s40arhhxSuw?usp=sharing

Thank you so much . Great work!
