### ISSUE TITLE
 extra point on the side of the ankle points 

### ISSUE THREAD

**Issue by senemaktas** [Wonder-Tree/PoseCamera#14]
Hi ,

I would like to inform you, there is an extra point on the side of the ankle points showing on images.

![1](https://user-images.githubusercontent.com/30393152/124555524-dc952580-de3f-11eb-91ee-730850d62092.png)
![2](https://user-images.githubusercontent.com/30393152/124555545-e1f27000-de3f-11eb-8356-3e0aa66004f0.png)
![3](https://user-images.githubusercontent.com/30393152/124555580-ed459b80-de3f-11eb-9de7-0f1210c8b137.png)

Thanks.

**Comment by usmankaiz** [comment]
@senemaktas, thank you for the updates, we are updating the SDK to fix the following issue you raised.

**Comment by musab1234** [comment]
@senemaktas We have updated the _pypi_ package with the current issue fixed, can you update the current _posecamera_ package and recheck the program.  you can use `pip install posecamera -U`  to upgrade current  _posecamera_ version.

**Comment by senemaktas** [comment]
> @senemaktas We have updated the _pypi_ package with the current issue fixed, can you update the current _posecamera_ package and recheck the program. you can use `pip install posecamera -U` to upgrade current _posecamera_ version.

Excellent, thank you.
