### ISSUE TITLE
multiple person pose estimation on images

### ISSUE THREAD

**Issue by senemaktas** [Wonder-Tree/PoseCamera#16]
Hi again,

I am working with your library nowadays. When I work with an image containing multiple people, it only gives value to a single person key points. For example:
```
 det = posecamera.pose_tracker.PoseTracker()

image = cv2.imread("/content/1.png")

pose = det(image)
for name, (y, x, score) in pose.keypoints.items():
    #cv2.circle(image, center_coordinates, radius, color, thickness)
    cv2.circle(image, (int(x), int(y)), 8, (243, 255, 51), -1)

img = cv2.resize(image, (250, 250))        
cv2_imshow(img)
```
![index](https://user-images.githubusercontent.com/30393152/125284303-f643da80-e321-11eb-9abc-cafa462fe119.png)

How can i get it for multiple person? Thank you.

**Comment by musab1234** [comment]
Hi @senemaktas , Thank you for trying out PoseCamera SDK.  Currently our main focus is on single person pose estimation, we are optimizing and make it more faster for low edge devices. We'll add multi-pose feature in near future. Stay tuned!

- [ ]  Multi person pose estimation

**Comment by senemaktas** [comment]
Thank you very much for notification! I am looking forward to see it !b @musab1234
