### ISSUE TITLE
xcb problems

### ISSUE THREAD

**Issue by Utopiah** [Wonder-Tree/PoseCamera#5]
On Linux with nvidia-docker2

```
fabien@fabien-CORSAIR-ONE-i160:~$ xhost +; docker run --name posecamera --rm --gpus all -e DISPLAY=$DISPLAY --device=/dev/video0:/dev/video0 wondertree/posecamera --video=0
access control disabled, clients can connect from any host
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/user/miniconda/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

Same for running on image rather than webcam :

```
fabien@fabien-CORSAIR-ONE-i160:~$ docker run --name posecamera --rm -e DISPLAY=$DISPLAY  wondertree/posecamera --images ./tmp/female_pose.jpg --cpu
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/user/miniconda/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

**Comment by musab1234** [comment]
Hi @Utopiah , please add `--net=host`  argument after `--rm` ,  for example: 
`docker run --name posecamera --rm --net=host -e DISPLAY=$DISPLAY  wondertree/posecamera --images ./tmp/female_pose.jpg --cpu`

**Comment by Utopiah** [comment]
Neat, thanks indeed `xhost +; docker run --name posecamera --rm --net=host --gpus all -e DISPLAY=$DISPLAY --device=/dev/video0:/dev/video0 wondertree/posecamera --video=0` worked. Here is the proof : 

![Screenshot_20201109_120049](https://user-images.githubusercontent.com/1076655/98533469-51996680-2283-11eb-91eb-a57a452432ed.png)
![Screenshot_20201109_120003](https://user-images.githubusercontent.com/1076655/98533473-52ca9380-2283-11eb-9e44-66340503de99.png)

**Comment by musab1234** [comment]
Glad it worked 👍, we'll add this fix in our README.
